### ISSUE TITLE
Log in second time

### ISSUE THREAD

**Issue by mikelnorth** [DevMtn-Due/due#5]
hey guys something super weird going on here, when I try to log back in I am getting an error.

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): error: operator does not exist: character varying = integer

I think it has to do with the deserializeUser in the server. 

also, it isn't letting me chose a different account to log in it just logs me in with the previously known account.

**Comment by AlexElls21** [comment]
I will get Travis on it...

**Comment by tbates93** [comment]
Nailed it. #6
